// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuuKhQkbLxUzoqtczxBcFTTmP5l1C8Hyo',
    appId: '1:524697476634:android:ab0d6173ab46ba6a997ba3',
    messagingSenderId: '524697476634',
    projectId: 'pokemon-e8b10',
    storageBucket: 'pokemon-e8b10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcGPeP-7G5Im9KlW3iTsKgZ_xSYZoXbro',
    appId: '1:524697476634:ios:5b96583ad786ea3c997ba3',
    messagingSenderId: '524697476634',
    projectId: 'pokemon-e8b10',
    storageBucket: 'pokemon-e8b10.firebasestorage.app',
    androidClientId: '524697476634-0iufo096k5lbakqoaaonvva7ba52f9qg.apps.googleusercontent.com',
    iosClientId: '524697476634-bs8os4v7nvbnoer0i050nlbtv663gcf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
